- name: Install mysql
  apt:
    name:
      - mysql-server
      - python3-pymysql
      - python3-pip

- name: install Configparser
  pip:
    name:
      - configparser
    executable: pip3

- name: Start mysql service
  service:
    name: mysql
    state: started
    enable: true

- name: Update password
  mysql_user:
    name: root
    password: root
    host: localhost
    state: present 
    check_implicit_admin: yes
    login_host: localhost
    login_unix_socket: /run/mysqld/mysqld.sock
               